apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fiap-toggle-eks-cluster
  region: us-east-1
  version: "1.35"

managedNodeGroups:
  - name: fiap-toggle-eks-cluster-nodes
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 4
    volumeSize: 20
    ssh:
      allow: true
      publicKeyName: dan
    labels:
      alpha.eksctl.io/cluster-name: fiap-toggle-eks-cluster

vpc:
  autoAllocateIPv6: true
  cidr: 10.11.0.0/16